### ISSUE TITLE
Option to have just a single cache file

### ISSUE THREAD

**Issue by vincerubinetti** [borisdiakur/memoize-fs#313]
I think it'd be nice to be able to have a single cache file instead of having a file for each individual cache key. This isn't the biggest deal in the world, and I don't expect it to happen since it would require a fundamental change in the way the library is written, but let me bring up why I think it's a bit of a pain.

In my case I have to commit my disk cache to my repository. When making PRs on GitHub, having _thousands_ of cache files, even if they're in their own separate folder, still really clogs up the diff view page. That's tons of extra files the reviewer has to minimize or otherwise ignore.

Similarly, when text-searching my repo in my IDE, I often get false positive matches in the caches, unless I type in an exclusion for the cache folder.

I'm sure there's other benefits to a single file as well that I'm not thinking of.

**Comment by borisdiakur** [comment]
Hey @vincerubinetti 👋🏻
you pretty much summed it up correctly: It would be a rather difficult task: How do you efficiently retrieve a specific cache from a single file containing many caches? How do you efficiently write to that file? What happens if many write operations happen all at once? Besides, the feature would cover a really rare use case: Adding cache files to version control seems strange, but I believe you have your reasons. For now, I'd rather not implement this feature, because I have no good ideas how to approach the questions above.
